secrets:
    AUTH0_TEST_USERNAME: ENC[AES256_GCM,data:lPddHbDVfWxaEW7ujLDnWdhIBMFj2hcp,iv:oG3Ebn8ym7g/Z7L3A3BTHRHIk+zzblZKvzMKYMPSfWI=,tag:wV7xJWbnLrj/UWj0fGGQCw==,type:str]
    AUTH0_TEST_PASSWORD: ENC[AES256_GCM,data:3tgQjqv5ktdnnGUQw5Lpuw==,iv:F8zYxqk5P0tV1Pvt6QBlho8H0wuX+K91pgwLzF+4kC8=,tag:HJ4s14d/u2KyP780wFDk/w==,type:str]
    AUTH0_CLIENT_ID: ENC[AES256_GCM,data:HevA8uFKCOPF8W/FRjSo/pyUFN66eXwvAxaqT5LdnT0=,iv:qpWNjsRSZ28lWQJGfMoGQvLY8KRKWv1dhR07vCgIvIU=,tag:x5BS26iacdBMv2ZkdCdr3A==,type:str]
    AUTH0_DOMAIN: ENC[AES256_GCM,data:2vv9ay+hC1kN46MG8E0v1Z3G7Dm0hMmLx1/AWg==,iv:9thZflFQ1yhf0jH3u6Om7RV7Y/qYzrTf82hoYrDvyG0=,tag:BUNuHJobt/NoR5FFQBIbIQ==,type:str]
    IMAGE_FACTORY_ENTERPRISE_STAGING_TOKEN: ENC[AES256_GCM,data:rq1myZjHYp5WT1doGUhGQSy/d58PpLhPGlB50ffMuTIO3WVPr8Vhn45qQqcuqvurHsiTgVXp1xdNPenc6zTGM0LOpmWeziXj+haeZkmwmonwFx1c1vx9wD8G+jLvjYudfCt7Hxc4uKKtApkhlhYFg3nW6ePS8u5CPY9IX/z7YGjWxSkCXbYNliCNMBhLzZwP8aoBO8ZkDcEKUVaJ7t4omilUdAFxhGz2esliIxPophLZyzLcqgN204uqgV37O4a7/HmxMLG7HrL5qzYgSSPvqSAG1Tzw7xd5MuWex4pgYpSqS5bX+lShQPXk7i45uOYr092BtunuQ1MLUtMTf5uYbYg5CF7YBd3lhntEIG7P4sAgR3Z8G4lPZbxwF8/35tIGLoQ8f8Iu8MGAV+lI67gu125tIK7hG8pEA5a9yIfCBbS+NmozFX2alROR53kCAM6UWP9NaOvfnAdtvu1iQHQpg5seLEwJ7QOtE19Eo57+10IQZTqcNj5dbg2FIjVLdd9udqxSWEca8ApzQOVMyzNPF3jcNcbvKbT+G9ZTU+oDAVk7BWTbBj8HpXZtDr67sfVp7P9zGI0SK8V1uY+//NXCrApMaWZRYjRJhLaXCkqkeT1eArWfmTCVHNR8X4Bmtv4Px5Q7E/CLlG4kopqEbIeHkEM8jOXKv0tBJQS27ppQEpmTseilcP6llvEL3LwXWovvkXZ7KYHceJ7Syx04tUfYf6+OsOZ+7dxdcAB77VTLgRJ2xTvcCvDC6DfeMEQLTEfe7fDQV6/NDXD3HLeWfrE0Gf6kT5NPyW6heYvBw//U,iv:cnaK3hR5TPQD5JlBb0TsVzgdX7ntvusSBguXKtIqGnQ=,tag:eqJHQ7GLQi5y1e/4rAcggA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRC9PWFJkK2FJa3N0UHlv
            WkJGQVZCVUl4NEhqRDdiUm03TC9NQTVmWm5vCmNFZGdCUE1OMzZiNnpoSnR0UVYx
            UVF2Rzg4VEdSdGNZdUNXd2V5UGdrOTAKLS0tIEQvNjVjUlRPZFBuK2M4dS9KYTFR
            a3QwZCtyZ0NBQXo4cmFRazVwWlZEWFkKIHUHaImxN+SgMVSd6pgMQyiAy+mTQAaQ
            mGIKj1vrDXs1FLAl5lkV7IxFkf51qqTk6rOxjv1zCzFYLATAr3t4eg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrpa9ujxxcj2u2gzfrzv8mxak4rts94a6y60ypurv6rs5cpr4e4sg95f0k
    lastmodified: "2026-09-10T22:43:35Z"
    mac: ENC[AES256_GCM,data:Wf7LVug+m6e/hS8yGe5Txjh32OByzyVaawTPi3lKNYxhAB5d5M+jDqz79LQRDy9YUalmmL6VJnqFN7a6Vg0lQciiUVuD2NR2eVEZAGGbxj3FMzUR6B3vQ1S/DUMDyv/rtFpVDb5vV3YUEPBwP/2B4uwnxlMbOujBebtfLLs8ZpA=,iv:64PqUR3/Em3GixH+sT7EQIgyVVq4zr9ZIikzn3oKL2k=,tag:08bKPN3ie7v/satS/tQgYQ==,type:str]
    pgp:
        - created_at: "2024-11-27T13:27:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D/dYBJRlWfQISAQdAWb3gbi9Rm9Ery5O4vjcms/Inx26KJ8SODWRZ1t/k7nkw
            I+u059duWr0e7O2ykSzDnGQA6Aj+HdhPoPcdnNlBWpy3raPwKzJ+X8kVIYp3qiba
            0lwB4HMtkNBpz91ErblPNWiVVVe3+G8LLJpDTpaVuPNsj1d3OgnKnWnVFK0b8FAL
            kQSmurQgKKbWZ7R6uhfWLINBR4ICZg51FViURfpWoUtlGvrL+nnbvmy9hQVGMQ==
            =7teE
            -----END PGP MESSAGE-----
          fp: 15D5721F5F5BAF121495363EFE042E3D4085A811
        - created_at: "2024-11-27T13:27:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D+EORkHurkvgSAQdAkbVUYD2I5MOoPjRjTRI6EfMlA8oEGsMu+ovxmEyMLwkw
            egHUl/oDTgovO+12mC/iRAhaKzV5fvCeZUTDbPB7BT+a2HsGyQEE2O4JYrSY/EMJ
            0lwBe8TdlHF9HUqwzHbRTo8UDbap0gpJ/KngXJ51m90Az6u4+lmpPgcgWSyJAnBF
            u/rjpjqobTmwR8Ea7NZpF3ZcoltlJLyd6w0O7JD5hd8nVWEhbN2KDHwKAnbneQ==
            =aBI7
            -----END PGP MESSAGE-----
          fp: CC51116A94490FA6FB3C18EB2401FCAE863A06CA
        - created_at: "2024-11-27T13:27:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DCsA/BhMt3V4SAQdAasIYIdDD+bb/JHfxT0yCMbxOu0JFB95rVSMTzLLw+BAw
            K8XVL7U+2EbmjO2OkTEbI80SEu//L/c/ZjmvTU8dt18WWMWb/FDWYGrw40KBMbts
            0lwBUk4UzZ38uDmnNPka1k6vBPWxvfIOHylbZYFoC4oLXEkghj70cPji6ZBUxpe1
            d6Avs0cXx5PLbM2lL/Rh/+9dAhSkl+Uzc5kEXfYPW0IBNlHaH1By+wsoVTgsGQ==
            =+zAf
            -----END PGP MESSAGE-----
          fp: 4919F560F0D35F80CF382D76E084A2DF1143C14D
        - created_at: "2024-11-27T13:27:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DRbry8yWl6IgSAQdAJoHdZndKL5N3KuO+gNofIpZYKhihf0L5MP+tG5LPKD0w
            Hhm5QOMjYNT7LjOTKtRb59ymKSP0oLiQMNvphw4q0IYsFz+l4UkanT6IO6K5tdvQ
            1GYBCQIQrIdQeujzcbTI2z9Iwh8RnBxdEhhBYSZMyrzBS7B2V5p0qpjaFojbI3oa
            A4uaNEpxnk59mfCuZeKHNURVHn0VT/jZdzalC7aQMk1h/7w6cjZLjJ/Skn5t1Obp
            mQKG7tBZzLo=
            =PH0s
            -----END PGP MESSAGE-----
          fp: 11177A43C6E3752E682AC690DBD13117B0A14E93
        - created_at: "2024-11-27T13:27:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DzfZC0UNQ1VgSAQdAZ0yc24RcLD0R7Bs4UPQTAfbp5Y/DtanIv7kOSjVtlAEw
            +F1qLNuwR0r1K9HLndgu0G5vi3L3ra8drb6YMKR7kXyN9RLXjDBt8gD3s386VGMa
            1GYBCQIQx6GailOK4BBn2H8HQqDTEgrsLj0ZhG6jOCwKpdPD3VoC4OWDJ0yzt72Z
            fwP3VgEH1IB+QF+XBJgdJsh54d79UDutBLxIYJAInQ3foxD3DOQ96D0onysA/qqh
            ZV7CB+9hCYc=
            =36ga
            -----END PGP MESSAGE-----
          fp: AA5213AF261C1977AF38B03A94B473337258BFD5
    unencrypted_suffix: _unencrypted
    version: 3.8.1
